# Required configs
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: 'mongodb+srv://bcvm.qddqqys.mongodb.net/bcvm?retryWrites=true&w=majority'

    # Local configuration (COMMENT BELOW OUT FOR PRODUCTION)
    username: postgres
    password: '0101'

